### ISSUE TITLE
Implement Persistence for text files

### ISSUE THREAD

**Issue by admarton** [CMDR14/IQuizt#2]
After creating the persistence interface, we can implement it for text files.
Format should be readable.
I suggest this format:
<QuizItem 1>

<QuizItem 2>

<...>

QuizItem:
\<Question>
\<Right Answer>
\<Wrong Answer 1>
\<Wrong Answer 2>
\<Wrong Answer 3>
\<Attempts> \<Count of correct answers>

**Comment by CMDR14** [comment]
Persistence now works for text files, will need some patches.
