### ISSUE TITLE
Create Model

### ISSUE THREAD

**Issue by admarton** [CMDR14/IQuizt#9]
Model stores active quiz and communicates with subsystems.

**Comment by admarton** [comment]
Create methods for mainwidget's menu options: MyProfile, EditQuiz, LoadExistingQuiz.
Check if mainwidget can change active widget. 
MyProfile -> Profile viewer widget
EditQuiz -> Quiz editor widget
LoadExistingQuiz -> Quiz set selector widget

**Comment by CMDR14** [comment]
Model created, has basic functions. Closing issue.
